### ISSUE TITLE
figure out how to parse pdf files extracted from url

### ISSUE THREAD

**Issue by ErvinRex** [MahinRahman8901/c10-Court-Transcript#10]
## Task Description

- Use py.pdf library to parse through pdf files and extract relevant information to be passed into db and GPT-API

## User Stories

- Users need only the relevant information to be displayed in our dashboard, doing this task will extract that information and pass any abstract/large texts to the API to be summarised.

## Relevant Files [If Available] 

-

**Comment by luciegamby-sigmalabs** [comment]
Need to parse:

- Judge Name
- Case Number
- Date

**Comment by ErvinRex** [comment]
Also parse:

- Introduction
- Conclusion
