### ISSUE TITLE
write dashboard "judge count over appointment date line graph" script

### ISSUE THREAD

**Issue by RachelPun** [MahinRahman8901/c10-Court-Transcript#132]
## Task Description

- 

## User Stories

- As a user of the dashboard, I want to be able to see, for certain gender, verdict, etc. settings, when the relevant judges were appointed and see if there is a pattern to it.

## Relevant Files [If Available] 

-

**Comment by ayeshaa63** [comment]
Is this graph necessary? Not sure what relevant insights it provides.
