### ISSUE TITLE
write dashboard "verdict waffle chart" script

### ISSUE THREAD

**Issue by RachelPun** [MahinRahman8901/c10-Court-Transcript#136]
## Task Description

- 

## User Stories

- As a user of the dashboard, I want to be able to see, for certain judge type, verdict, etc. settings, a visualisation of the relative amount of cases of that combination of settings and the ratio between claimant and defendant wins, and see if there is a pattern to it.

## Relevant Files [If Available] 

-

**Comment by ayeshaa63** [comment]
Is this waffle chart going to summarise every single verdict or will it be by judge? @RachelPun
