### ISSUE TITLE
Fix pipeline bug

### ISSUE THREAD

**Issue by luciegamby-sigmalabs** [MahinRahman8901/c10-Court-Transcript#145]
## Task Description

- Lambda function won't work due to an error with cleaning dates

## User Stories

- As a developer, I need to make sure my dates are cleaned correctly, so that they can be correctly inputted into the dataframe

## Relevant Files [If Available] 

- 'transform.py'

**Comment by luciegamby-sigmalabs** [comment]
Date bug fixed, issues with load now. Attempting to load a case where the case_no already exists in db.

**Comment by ErvinRex** [comment]
Case_no_id comes under different html division names, this may require a bunch of if statements to locate the case_no_id or just stick to the most commonly used "judge-header__case-number" and disregard all other types.

We may lose many cases this way though.

**Comment by luciegamby-sigmalabs** [comment]
Is this during web-scraping?

**Comment by ErvinRex** [comment]
Yeah, and then I went to check what headers the case_no_id could come under for the first page, so far I see one that has a different header name

**Comment by luciegamby-sigmalabs** [comment]
Maybe I could do a similar thing for when I check titles in the db (in extract.py), but also check for case_no_id?

**Comment by ErvinRex** [comment]
As in dropping cases when you can't find the title?

**Comment by luciegamby-sigmalabs** [comment]
Like querying the database to see if the case_no is already in there - and dropping the case if so.
