### ISSUE TITLE
create script to scrape/extract judges

### ISSUE THREAD

**Issue by RachelPun** [MahinRahman8901/c10-Court-Transcript#19]
## Task Description

- scrape judge information from [List of members of the courts judiciary](https://www.judiciary.uk/about-the-judiciary/who-are-the-judiciary/list-of-members-of-the-judiciary/)
- upload data to database
- Determine how we want to match judges to pdf of each case

## User Stories

- As data engineers of this project, we need to extract information on the judges, to analyse patterns of court events with more context, e.g. to show potential biases of judges.
- As a member of the general public, I need to understand court events with context of the judges, to understand who have influence on court decisions and how.

## Relevant Files [If Available] 

-

**Comment by luciegamby-sigmalabs** [comment]
If a judge has multiple appointment dates - go with the first date. This will give us more information in terms of how long they have been a judge for.
