### ISSUE TITLE
Decide on how we assess bias of judges

### ISSUE THREAD

**Issue by ErvinRex** [MahinRahman8901/c10-Court-Transcript#21]
## Task Description

- We have a number of variables we can take a look at, but this is important when creating our database ERD.

1. Judge location
2. Judge appointment
3. Think of more points

## User Stories

- When we dashboard to stakeholders, numbers and graphs are an easy way to visualise bias, to do this we need to find variables to be used for assessing bias. 

## Relevant Files [If Available] 

-

**Comment by luciegamby-sigmalabs** [comment]
Decided that we can't assess biases per se. We'll look at things on a per-judge basis and show a judge's tendencies

**Comment by ErvinRex** [comment]
Decided that we will just look at how a specific judge favours (in favour of claimant or defendant) for now.
