### ISSUE TITLE
Create Skeleton Presentation

### ISSUE THREAD

**Issue by ayeshaa63** [MahinRahman8901/c10-Court-Transcript#22]
## Task Description

Storyboard the presentation with the intended slides and the intended content (no need for actual content yet).

## User Stories

As a presenter I need an idea of what will be in the presentation so the team can build on it.

**Comment by MahinRahman8901** [comment]
https://www.canva.com/design/DAGDOYh_YSI/xnWjdm9L7nkEk4Xk8qXa_g/edit?utm_content=DAGDOYh_YSI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Can be viewed here
