### ISSUE TITLE
Dockerise the lambda script of ETL

### ISSUE THREAD

**Issue by ErvinRex** [MahinRahman8901/c10-Court-Transcript#61]
## Task Description

- To use the ETL script, it must be dockerised as an image to be uploaded on AWS ECR for storage to then be extracted by its related services.

## User Stories

- Having a cloud storage service holding the image takes control out of the hands of users, however, they do not need to see what is going on behind the scenes, only that the end product works.

## Relevant Files [If Available] 

-

**Comment by MahinRahman8901** [comment]
Completed dockerisation of ETL script
