### ISSUE TITLE
modify schema.sql and seeds.sql + reset database

### ISSUE THREAD

**Issue by RachelPun** [MahinRahman8901/c10-Court-Transcript#90]
## Task Description

- add unique constraint to circuit names and judge type names
- run schema.sql and seeds.sql to reset the database

## User Stories

- As data engineers, we need to build a solid schema, to ensure data accuracy/integrity

## Relevant Files [If Available] 

-

**Comment by ErvinRex** [comment]
closed by #81 and #83
