### ISSUE TITLE
Check for judges every month

### ISSUE THREAD

**Issue by MahinRahman8901** [MahinRahman8901/c10-Court-Transcript#97]
## Task Description

- We need to create a system where the pipeline runs every month for the judges and checks if the judges in the database already exists if they don't then they add them.

## User Stories

- As an engineer, we need to make sure our data is up to date, so that our dashboard has up to date information

## Relevant Files [If Available] 

-

**Comment by luciegamby-sigmalabs** [comment]
Turn event-bridge back on when done

**Comment by luciegamby-sigmalabs** [comment]
Event bridge is turned on, slight terraform issue though. Need to change the target arn.
